apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-app

resources:
  - namespace.yaml
  - 00-pvc.yaml
  - 01-petclinic-deployment.yaml
  - 02-petclinic-svc.yaml
  - 03-petclinic-route.yaml

images:
  - name: petclinic
    newName: quay.io/pittar/petclinic
    newTag: metrics
