apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: backup-bucket
  namespace: openshift-adp
spec:
  additionalConfig:
    bucketclass: noobaa-default-bucket-class
  generateBucketName: acm-object-storage
  storageClassName: openshift-storage.noobaa.io