apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: default-dpa
  namespace: openshift-adp
spec:
  configuration:
    restic:
      enable: true
    velero:
      defaultPlugins:
        - openshift
        - aws
  backupLocations:
    - velero:
        default: true
        provider: aws
        credential:
            name: cloud-credentials
            key: cloud
        objectStorage:
            bucket: <your bucket name>
            prefix: velero
        config:
            insecureSkipTLSVerify: "true"
            profile: default
            region: "noobaa"
            s3ForcePathStyle: "true"
            s3Url: http://s3.openshift-storage.svc